name: First Work Flow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Welcome to Git Hub Actions World !!!"
      - name: Print Awaiting
        run: echo "This is Just a beginning and much more is there to learn....."
    
  
